spring:
  application:
    name: GestorRH-Admin
  profiles:
    active: dev

server:
  port: 9090
  servlet:
    context-path: /admin
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "*"
